FROM maven:3-jdk-8-alpine

# Install Some tool
RUN apk add --no-cache git

# Install Docker client
RUN curl -L -o /tmp/docker-latest.tgz \
    "https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz" \
  && tar xzf /tmp/docker-latest.tgz -C /tmp/ \
  && mv /tmp/docker/* /usr/bin/ \
  && chmod a+x /usr/bin/docker* \
  && rm -rf /tmp/docker*

RUN echo '<settings><localRepository>/maven-cache/repository</localRepository></settings>' \
  > /settings.xml

VOLUME ["/maven-cache"]
