pipeline {
    agent any

    stages {
        stage('Create marker') {
            steps {
                echo 'Creating..'
                # This is a workaround as these variables are not loaded properly
                script {
                    env.GIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                }
                echo "${env.GIT_COMMIT}"
                sh 'bash scripts/generate_marker.sh'
                sh 'cat ./marker.txt'
            }
        }
        stage('Deploy marker') {
            steps {
                echo 'Deploying....'
                archive 'marker.txt'
            }
        }
    }
}