pipeline {
    agent any

    stages {
        stage('Create marker') {
            steps {
                echo 'Creating..'
                sh 'bash scripts/generate_marker.sh'
            }
        }
        stage('Deploy marker') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}